In [146]:
import pandas as pd
import numpy as np

In [185]:
data_frame = pd.read_csv("Latest_Rankings.csv", index_col = 'Nation')
data_frame.head(25)

               Rank  Squad_Size  Avg_Age Total Value Confideration  Points
Nation
Belgium           1          31     27.4    $793.10m          UEFA    1780
France            2          26     27.6     $1.17bn          UEFA    1755
Brazil            3          25     27.6     $1.03bn      CONMEBOL    1743
England           4          25     25.6     $1.11bn          UEFA    1670
Portugal          5          24     27.4    $845.90m          UEFA    1662
Spain             6          24     26.4    $940.50m          UEFA    1645
Argentina         7          22     27.9    $581.90m      CONMEBOL    1642
Uruguay           8          35     27.0    $498.16m      CONMEBOL    1639
Mexico            9          22     27.8    $190.96m      CONCACAF    1632
Italy            10          29     27.1    $893.20m          UEFA    1625
Croatia          11          25     28.2    $385.00m          UEFA    1617
Denmark          12          27     27.7    $330.33m          UEFA    1614
Germany          13          23     26.3     $1.04bn          UEFA    1610
Netherlands      14          24     27.4    $566.23m          UEFA    1609
Colombia         15          27     27.6    $337.40m      CONMEBOL    1601
Switzerland      16          23     26.9    $289.30m          UEFA    1593
Chile            17          24     28.1     $39.93m      CONMEBOL    1567
Wales            18          25     25.2    $137.97m          UEFA    1562
Poland           19          25     26.6    $300.19m          UEFA    1559
Senegal          20          23     26.4    $253.94m           CAF    1558
Sweden           20          25     28.6    $222.97m          UEFA    1558
United States    22          26     23.3    $229.90m      CONCACAF    1548
Austria          23          29     27.2    $333.82m          UEFA    1531
Ukraine          24          23     26.4    $140.14m          UEFA    1521
Peru             25          36     28.7     $94.19m      CONMEBOL    1512

In [148]:
data_frame.dtypes

Rank               int64
Squad_Size         int64
Avg_Age          float64
Total Value       object
Confideration     object
Points             int64
dtype: object

In [149]:
# Merge_data_frame= data_frame.set_index('Nation')
# Merge_data_frame

In [187]:
#AFC_teams = pd.read_csv("AFC.csv")
#AFC_teams.head(10)
#North_America_teams = pd.read_csv("North_America.csv")
#North_America_teams
#South_America_teams = pd.read_csv("South_America.csv")
#South_America_teams
#Oceania_Teams = pd.read_csv("Oceania.csv")
#Oceania_Teams
UEFA_Teams = pd.read_csv("UEFA.csv")
UEFA_Teams

                 Nation  Pots
0               Belgium     1
1                France     1
2               England     1
3              Portugal     1
4                 Spain     1
5                 Italy     1
6               Croatia     1
7               Denmark     1
8               Germany     1
9           Netherlands     1
10          Switzerland     2
11                Wales     2
12               Poland     2
13               Sweden     2
14              Austria     2
15              Ukraine     2
16               Serbia     2
17               Turkey     2
18             Slovakia     2
19              Romania     2
20               Russia     3
21              Hungary     3
22  Republic of Ireland     3
23       Czech Republic     3
24               Norway     3
25     Northern Ireland     3
26              Iceland     3
27             Scotland     3
28               Greece     3
29              Finland     4
30               Bosnia     4
31             Slovenia     4
32           Montenegro     4
33              Albania     4
34             Bulgaria     4
35               Israel     4
36              Belarus     4
37              Georgia     4
38           Luxembourg     4
39              Armenia     5
40               Cyprus     5
41        Faroe Islands     5
42           Azerbaijan     5
43              Estonia     5

In [151]:
#AFC_teams.dtypes

In [188]:
#team_details = pd.merge(AFC_teams, data_frame, left_on='Nation', right_index =True ,how='left')
#team_details = pd.merge(North_America_teams, data_frame, left_on='Nation', right_index=True, how='left')
#team_details = pd.merge(South_America_teams, data_frame, left_on='Nation', right_index=True, how='left')
#team_details = pd.merge(Oceania_Teams, data_frame, left_on='Nation', right_index=True, how='left')
team_details = pd.merge(UEFA_Teams, data_frame, left_on='Nation', right_index=True, how='left')
team_details

,Nation,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points
0,Belgium,1,1,31,27.4,$793.10m,UEFA,1780
1,France,1,2,26,27.6,$1.17bn,UEFA,1755
2,England,1,4,25,25.6,$1.11bn,UEFA,1670
3,Portugal,1,5,24,27.4,$845.90m,UEFA,1662
4,Spain,1,6,24,26.4,$940.50m,UEFA,1645
5,Italy,1,10,29,27.1,$893.20m,UEFA,1625
6,Croatia,1,11,25,28.2,$385.00m,UEFA,1617
7,Denmark,1,12,27,27.7,$330.33m,UEFA,1614
8,Germany,1,13,23,26.3,$1.04bn,UEFA,1610
9,Netherlands,1,14,24,27.4,$566.23m,UEFA,1609
10,Switzerland,2,16,23,26.9,$289.30m,UEFA,1593
11,Wales,2,18,25,25.2,$137.97m,UEFA,1562
12,Poland,2,19,25,26.6,$300.19m,UEFA,1559
13,Sweden,2,20,25,28.6,$222.97m,UEFA,1558
14,Austria,2,23,29,27.2,$333.82m,UEFA,1531
15,Ukraine,2,24,23,26.4,$140.14m,UEFA,1521
16,Serbia,2,30,30,26.4,$383.41m,UEFA,1492
17,Turkey,2,32,24,25.9,$249.81m,UEFA,1487
18,Slovakia,2,34,29,27.7,$135.47m,UEFA,1478
19,Romania,2,37,24,27.7,$105.44m,UEFA,1466
20,Russia,3,39,26,28.4,$165.66m,UEFA,1461
21,Hungary,3,40,24,28.3,$65.84m,UEFA,1460
22,Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456
23,Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456
24,Norway,3,44,26,26.8,$270.16m,UEFA,1450
25,Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440
26,Iceland,3,46,23,29.0,$41.75m,UEFA,1438
27,Scotland,3,48,26,28.2,$274.34m,UEFA,1436
28,Greece,3,53,28,26.2,$114.46m,UEFA,1413
29,Finland,4,55,25,28.7,$32.89m,UEFA,1411
30,Bosnia,4,56,23,26.7,$87.12m,UEFA,1410
31,Slovenia,4,62,25,27.8,$148.34m,UEFA,1379
32,Montenegro,4,63,37,28.1,$70.51m,UEFA,1370
33,Albania,4,66,28,26.1,$117.89m,UEFA,1360
34,Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350
35,Israel,4,87,23,27.3,$49.89m,UEFA,1279
36,Belarus,4,88,25,27.2,$15.84m,UEFA,1269
37,Georgia,4,89,27,26.9,$57.09m,UEFA,1267
38,Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235
39,Armenia,5,99,23,27.6,$18.65m,UEFA,1233
40,Cyprus,5,100,28,25.4,$18.65m,UEFA,1224
41,Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183
42,Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180
43,Estonia,5,108,27,26.3,$5.39m,UEFA,1180

In [189]:
players_df = pd.read_csv("players_20.csv", index_col="sofifa_id")
players_df

,short_name,nationality,overall,player_positions,work_rate,team_position
sofifa_id,,,,,,
158023,L. Messi,Argentina,94,"RW, CF, ST",Medium/Low,RW
20801,Cristiano Ronaldo,Portugal,93,"ST, LW",High/Low,LW
190871,Neymar Jr,Brazil,92,"LW, CAM",High/Medium,CAM
200389,J. Oblak,Slovenia,91,GK,Medium/Medium,GK
183277,E. Hazard,Belgium,91,"LW, CF",High/Medium,LW
...,...,...,...,...,...,...
245006,Shao Shuai,China PR,48,CB,Medium/High,RES
250995,Xiao Mingjie,China PR,48,CB,Medium/Medium,SUB
252332,Zhang Wei,China PR,48,CM,Low/Medium,SUB
251110,Wang Haijian,China PR,48,CM,Low/Low,SUB
233449,Pan Ximing,China PR,48,CM,Medium/Medium,SUB

In [190]:
team_details = team_details.set_index("Nation")
team_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points
Nation,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780
France,1,2,26,27.6,$1.17bn,UEFA,1755
England,1,4,25,25.6,$1.11bn,UEFA,1670
Portugal,1,5,24,27.4,$845.90m,UEFA,1662
Spain,1,6,24,26.4,$940.50m,UEFA,1645
Italy,1,10,29,27.1,$893.20m,UEFA,1625
Croatia,1,11,25,28.2,$385.00m,UEFA,1617
Denmark,1,12,27,27.7,$330.33m,UEFA,1614
Germany,1,13,23,26.3,$1.04bn,UEFA,1610
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609
Switzerland,2,16,23,26.9,$289.30m,UEFA,1593
Wales,2,18,25,25.2,$137.97m,UEFA,1562
Poland,2,19,25,26.6,$300.19m,UEFA,1559
Sweden,2,20,25,28.6,$222.97m,UEFA,1558
Austria,2,23,29,27.2,$333.82m,UEFA,1531
Ukraine,2,24,23,26.4,$140.14m,UEFA,1521
Serbia,2,30,30,26.4,$383.41m,UEFA,1492
Turkey,2,32,24,25.9,$249.81m,UEFA,1487
Slovakia,2,34,29,27.7,$135.47m,UEFA,1478
Romania,2,37,24,27.7,$105.44m,UEFA,1466
Russia,3,39,26,28.4,$165.66m,UEFA,1461
Hungary,3,40,24,28.3,$65.84m,UEFA,1460
Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456
Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456
Norway,3,44,26,26.8,$270.16m,UEFA,1450
Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440
Iceland,3,46,23,29.0,$41.75m,UEFA,1438
Scotland,3,48,26,28.2,$274.34m,UEFA,1436
Greece,3,53,28,26.2,$114.46m,UEFA,1413
Finland,4,55,25,28.7,$32.89m,UEFA,1411
Bosnia,4,56,23,26.7,$87.12m,UEFA,1410
Slovenia,4,62,25,27.8,$148.34m,UEFA,1379
Montenegro,4,63,37,28.1,$70.51m,UEFA,1370
Albania,4,66,28,26.1,$117.89m,UEFA,1360
Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350
Israel,4,87,23,27.3,$49.89m,UEFA,1279
Belarus,4,88,25,27.2,$15.84m,UEFA,1269
Georgia,4,89,27,26.9,$57.09m,UEFA,1267
Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235
Armenia,5,99,23,27.6,$18.65m,UEFA,1233
Cyprus,5,100,28,25.4,$18.65m,UEFA,1224
Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183
Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180
Estonia,5,108,27,26.3,$5.39m,UEFA,1180

In [191]:
grouped_players_df = players_df.groupby('nationality')['overall'].agg(['median', 'count'])
grouped_players_df.head(30)

                      median  count
nationality
Afghanistan             62.0      2
Albania                 68.0     43
Algeria                 71.5     50
Angola                  70.5     16
Antigua & Barbuda       62.0      7
Argentina               70.0    886
Armenia                 67.0      8
Australia               63.0    196
Austria                 65.0    319
Azerbaijan              64.0      6
Bahrain                 72.0      1
Barbados                64.0      1
Belgium                 68.0    268
Belize                  66.0      1
Benin                   68.0     15
Bermuda                 62.0      3
Bolivia                 66.0     23
Bosnia Herzegovina      69.0     66
Brazil                  71.0    824
Bulgaria                64.0     41
Burkina Faso            66.0     16
Burundi                 65.0      4
Cameroon                69.0     78
Canada                  65.0     61
Cape Verde              71.0     20
Central African Rep.    69.0      4
Chad                    73.0      1
Chile                   66.0    370
China PR                60.0    373
Chinese Taipei          66.0      1

In [192]:
team_player_details = pd.merge(team_details, grouped_players_df, left_on='Nation', right_index=True, how='left').fillna(0)
team_player_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count
Nation,,,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780,68.0,268.0
France,1,2,26,27.6,$1.17bn,UEFA,1755,67.0,984.0
England,1,4,25,25.6,$1.11bn,UEFA,1670,63.0,1667.0
Portugal,1,5,24,27.4,$845.90m,UEFA,1662,70.0,344.0
Spain,1,6,24,26.4,$940.50m,UEFA,1645,69.0,1035.0
Italy,1,10,29,27.1,$893.20m,UEFA,1625,68.0,732.0
Croatia,1,11,25,28.2,$385.00m,UEFA,1617,69.0,126.0
Denmark,1,12,27,27.7,$330.33m,UEFA,1614,64.0,345.0
Germany,1,13,23,26.3,$1.04bn,UEFA,1610,66.0,1216.0
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609,67.0,416.0
Switzerland,2,16,23,26.9,$289.30m,UEFA,1593,65.0,229.0
Wales,2,18,25,25.2,$137.97m,UEFA,1562,65.0,117.0
Poland,2,19,25,26.6,$300.19m,UEFA,1559,64.0,324.0
Sweden,2,20,25,28.6,$222.97m,UEFA,1558,64.0,358.0
Austria,2,23,29,27.2,$333.82m,UEFA,1531,65.0,319.0
Ukraine,2,24,23,26.4,$140.14m,UEFA,1521,70.0,69.0
Serbia,2,30,30,26.4,$383.41m,UEFA,1492,70.0,139.0
Turkey,2,32,24,25.9,$249.81m,UEFA,1487,67.0,294.0
Slovakia,2,34,29,27.7,$135.47m,UEFA,1478,69.0,54.0
Romania,2,37,24,27.7,$105.44m,UEFA,1466,64.0,287.0
Russia,3,39,26,28.4,$165.66m,UEFA,1461,70.0,81.0
Hungary,3,40,24,28.3,$65.84m,UEFA,1460,70.0,35.0
Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456,61.0,348.0
Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456,72.0,102.0
Norway,3,44,26,26.8,$270.16m,UEFA,1450,63.5,350.0
Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440,64.0,81.0
Iceland,3,46,23,29.0,$41.75m,UEFA,1438,69.0,46.0
Scotland,3,48,26,28.2,$274.34m,UEFA,1436,65.0,277.0
Greece,3,53,28,26.2,$114.46m,UEFA,1413,70.0,96.0
Finland,4,55,25,28.7,$32.89m,UEFA,1411,63.0,72.0
Bosnia,4,56,23,26.7,$87.12m,UEFA,1410,0.0,0.0
Slovenia,4,62,25,27.8,$148.34m,UEFA,1379,68.0,61.0
Montenegro,4,63,37,28.1,$70.51m,UEFA,1370,67.0,33.0
Albania,4,66,28,26.1,$117.89m,UEFA,1360,68.0,43.0
Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350,64.0,41.0
Israel,4,87,23,27.3,$49.89m,UEFA,1279,70.0,16.0
Belarus,4,88,25,27.2,$15.84m,UEFA,1269,0.0,0.0
Georgia,4,89,27,26.9,$57.09m,UEFA,1267,68.0,25.0
Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235,65.0,9.0
Armenia,5,99,23,27.6,$18.65m,UEFA,1233,67.0,8.0
Cyprus,5,100,28,25.4,$18.65m,UEFA,1224,63.0,11.0
Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183,65.0,5.0
Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180,64.0,6.0
Estonia,5,108,27,26.3,$5.39m,UEFA,1180,65.0,6.0

In [193]:
team_player_details['Rank'] = team_player_details['Rank']
team_player_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count
Nation,,,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780,68.0,268.0
France,1,2,26,27.6,$1.17bn,UEFA,1755,67.0,984.0
England,1,4,25,25.6,$1.11bn,UEFA,1670,63.0,1667.0
Portugal,1,5,24,27.4,$845.90m,UEFA,1662,70.0,344.0
Spain,1,6,24,26.4,$940.50m,UEFA,1645,69.0,1035.0
Italy,1,10,29,27.1,$893.20m,UEFA,1625,68.0,732.0
Croatia,1,11,25,28.2,$385.00m,UEFA,1617,69.0,126.0
Denmark,1,12,27,27.7,$330.33m,UEFA,1614,64.0,345.0
Germany,1,13,23,26.3,$1.04bn,UEFA,1610,66.0,1216.0
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609,67.0,416.0
Switzerland,2,16,23,26.9,$289.30m,UEFA,1593,65.0,229.0
Wales,2,18,25,25.2,$137.97m,UEFA,1562,65.0,117.0
Poland,2,19,25,26.6,$300.19m,UEFA,1559,64.0,324.0
Sweden,2,20,25,28.6,$222.97m,UEFA,1558,64.0,358.0
Austria,2,23,29,27.2,$333.82m,UEFA,1531,65.0,319.0
Ukraine,2,24,23,26.4,$140.14m,UEFA,1521,70.0,69.0
Serbia,2,30,30,26.4,$383.41m,UEFA,1492,70.0,139.0
Turkey,2,32,24,25.9,$249.81m,UEFA,1487,67.0,294.0
Slovakia,2,34,29,27.7,$135.47m,UEFA,1478,69.0,54.0
Romania,2,37,24,27.7,$105.44m,UEFA,1466,64.0,287.0
Russia,3,39,26,28.4,$165.66m,UEFA,1461,70.0,81.0
Hungary,3,40,24,28.3,$65.84m,UEFA,1460,70.0,35.0
Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456,61.0,348.0
Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456,72.0,102.0
Norway,3,44,26,26.8,$270.16m,UEFA,1450,63.5,350.0
Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440,64.0,81.0
Iceland,3,46,23,29.0,$41.75m,UEFA,1438,69.0,46.0
Scotland,3,48,26,28.2,$274.34m,UEFA,1436,65.0,277.0
Greece,3,53,28,26.2,$114.46m,UEFA,1413,70.0,96.0
Finland,4,55,25,28.7,$32.89m,UEFA,1411,63.0,72.0
Bosnia,4,56,23,26.7,$87.12m,UEFA,1410,0.0,0.0
Slovenia,4,62,25,27.8,$148.34m,UEFA,1379,68.0,61.0
Montenegro,4,63,37,28.1,$70.51m,UEFA,1370,67.0,33.0
Albania,4,66,28,26.1,$117.89m,UEFA,1360,68.0,43.0
Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350,64.0,41.0
Israel,4,87,23,27.3,$49.89m,UEFA,1279,70.0,16.0
Belarus,4,88,25,27.2,$15.84m,UEFA,1269,0.0,0.0
Georgia,4,89,27,26.9,$57.09m,UEFA,1267,68.0,25.0
Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235,65.0,9.0
Armenia,5,99,23,27.6,$18.65m,UEFA,1233,67.0,8.0
Cyprus,5,100,28,25.4,$18.65m,UEFA,1224,63.0,11.0
Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183,65.0,5.0
Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180,64.0,6.0
Estonia,5,108,27,26.3,$5.39m,UEFA,1180,65.0,6.0

In [194]:
max_rank = team_player_details.max()['Rank']
max_rank

108

In [195]:
min_rank = team_player_details.min()['Rank']
min_rank

1

In [196]:
team_player_details['Normalize_Rank'] = (max_rank - team_player_details['Rank']) / (max_rank - min_rank)
team_player_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank
Nation,,,,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780,68.0,268.0,1.000000
France,1,2,26,27.6,$1.17bn,UEFA,1755,67.0,984.0,0.990654
England,1,4,25,25.6,$1.11bn,UEFA,1670,63.0,1667.0,0.971963
Portugal,1,5,24,27.4,$845.90m,UEFA,1662,70.0,344.0,0.962617
Spain,1,6,24,26.4,$940.50m,UEFA,1645,69.0,1035.0,0.953271
Italy,1,10,29,27.1,$893.20m,UEFA,1625,68.0,732.0,0.915888
Croatia,1,11,25,28.2,$385.00m,UEFA,1617,69.0,126.0,0.906542
Denmark,1,12,27,27.7,$330.33m,UEFA,1614,64.0,345.0,0.897196
Germany,1,13,23,26.3,$1.04bn,UEFA,1610,66.0,1216.0,0.887850
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609,67.0,416.0,0.878505
Switzerland,2,16,23,26.9,$289.30m,UEFA,1593,65.0,229.0,0.859813
Wales,2,18,25,25.2,$137.97m,UEFA,1562,65.0,117.0,0.841121
Poland,2,19,25,26.6,$300.19m,UEFA,1559,64.0,324.0,0.831776
Sweden,2,20,25,28.6,$222.97m,UEFA,1558,64.0,358.0,0.822430
Austria,2,23,29,27.2,$333.82m,UEFA,1531,65.0,319.0,0.794393
Ukraine,2,24,23,26.4,$140.14m,UEFA,1521,70.0,69.0,0.785047
Serbia,2,30,30,26.4,$383.41m,UEFA,1492,70.0,139.0,0.728972
Turkey,2,32,24,25.9,$249.81m,UEFA,1487,67.0,294.0,0.710280
Slovakia,2,34,29,27.7,$135.47m,UEFA,1478,69.0,54.0,0.691589
Romania,2,37,24,27.7,$105.44m,UEFA,1466,64.0,287.0,0.663551
Russia,3,39,26,28.4,$165.66m,UEFA,1461,70.0,81.0,0.644860
Hungary,3,40,24,28.3,$65.84m,UEFA,1460,70.0,35.0,0.635514
Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456,61.0,348.0,0.616822
Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456,72.0,102.0,0.616822
Norway,3,44,26,26.8,$270.16m,UEFA,1450,63.5,350.0,0.598131
Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440,64.0,81.0,0.588785
Iceland,3,46,23,29.0,$41.75m,UEFA,1438,69.0,46.0,0.579439
Scotland,3,48,26,28.2,$274.34m,UEFA,1436,65.0,277.0,0.560748
Greece,3,53,28,26.2,$114.46m,UEFA,1413,70.0,96.0,0.514019
Finland,4,55,25,28.7,$32.89m,UEFA,1411,63.0,72.0,0.495327
Bosnia,4,56,23,26.7,$87.12m,UEFA,1410,0.0,0.0,0.485981
Slovenia,4,62,25,27.8,$148.34m,UEFA,1379,68.0,61.0,0.429907
Montenegro,4,63,37,28.1,$70.51m,UEFA,1370,67.0,33.0,0.420561
Albania,4,66,28,26.1,$117.89m,UEFA,1360,68.0,43.0,0.392523
Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350,64.0,41.0,0.373832
Israel,4,87,23,27.3,$49.89m,UEFA,1279,70.0,16.0,0.196262
Belarus,4,88,25,27.2,$15.84m,UEFA,1269,0.0,0.0,0.186916
Georgia,4,89,27,26.9,$57.09m,UEFA,1267,68.0,25.0,0.177570
Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235,65.0,9.0,0.093458
Armenia,5,99,23,27.6,$18.65m,UEFA,1233,67.0,8.0,0.084112
Cyprus,5,100,28,25.4,$18.65m,UEFA,1224,63.0,11.0,0.074766
Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183,65.0,5.0,0.009346
Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180,64.0,6.0,0.000000
Estonia,5,108,27,26.3,$5.39m,UEFA,1180,65.0,6.0,0.000000

In [197]:
team_player_details['Above_Median_Count'] = team_player_details['count']/ 2 
team_player_details['Above_Median_Count'] =team_player_details['Above_Median_Count'].astype("int32")
team_player_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780,68.0,268.0,1.000000,134
France,1,2,26,27.6,$1.17bn,UEFA,1755,67.0,984.0,0.990654,492
England,1,4,25,25.6,$1.11bn,UEFA,1670,63.0,1667.0,0.971963,833
Portugal,1,5,24,27.4,$845.90m,UEFA,1662,70.0,344.0,0.962617,172
Spain,1,6,24,26.4,$940.50m,UEFA,1645,69.0,1035.0,0.953271,517
Italy,1,10,29,27.1,$893.20m,UEFA,1625,68.0,732.0,0.915888,366
Croatia,1,11,25,28.2,$385.00m,UEFA,1617,69.0,126.0,0.906542,63
Denmark,1,12,27,27.7,$330.33m,UEFA,1614,64.0,345.0,0.897196,172
Germany,1,13,23,26.3,$1.04bn,UEFA,1610,66.0,1216.0,0.887850,608
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609,67.0,416.0,0.878505,208
Switzerland,2,16,23,26.9,$289.30m,UEFA,1593,65.0,229.0,0.859813,114
Wales,2,18,25,25.2,$137.97m,UEFA,1562,65.0,117.0,0.841121,58
Poland,2,19,25,26.6,$300.19m,UEFA,1559,64.0,324.0,0.831776,162
Sweden,2,20,25,28.6,$222.97m,UEFA,1558,64.0,358.0,0.822430,179
Austria,2,23,29,27.2,$333.82m,UEFA,1531,65.0,319.0,0.794393,159
Ukraine,2,24,23,26.4,$140.14m,UEFA,1521,70.0,69.0,0.785047,34
Serbia,2,30,30,26.4,$383.41m,UEFA,1492,70.0,139.0,0.728972,69
Turkey,2,32,24,25.9,$249.81m,UEFA,1487,67.0,294.0,0.710280,147
Slovakia,2,34,29,27.7,$135.47m,UEFA,1478,69.0,54.0,0.691589,27
Romania,2,37,24,27.7,$105.44m,UEFA,1466,64.0,287.0,0.663551,143
Russia,3,39,26,28.4,$165.66m,UEFA,1461,70.0,81.0,0.644860,40
Hungary,3,40,24,28.3,$65.84m,UEFA,1460,70.0,35.0,0.635514,17
Republic of Ireland,3,42,27,26.4,$105.38m,UEFA,1456,61.0,348.0,0.616822,174
Czech Republic,3,42,25,28.2,$176.50m,UEFA,1456,72.0,102.0,0.616822,51
Norway,3,44,26,26.8,$270.16m,UEFA,1450,63.5,350.0,0.598131,175
Northern Ireland,3,45,27,27.4,$50.22m,UEFA,1440,64.0,81.0,0.588785,40
Iceland,3,46,23,29.0,$41.75m,UEFA,1438,69.0,46.0,0.579439,23
Scotland,3,48,26,28.2,$274.34m,UEFA,1436,65.0,277.0,0.560748,138
Greece,3,53,28,26.2,$114.46m,UEFA,1413,70.0,96.0,0.514019,48
Finland,4,55,25,28.7,$32.89m,UEFA,1411,63.0,72.0,0.495327,36
Bosnia,4,56,23,26.7,$87.12m,UEFA,1410,0.0,0.0,0.485981,0
Slovenia,4,62,25,27.8,$148.34m,UEFA,1379,68.0,61.0,0.429907,30
Montenegro,4,63,37,28.1,$70.51m,UEFA,1370,67.0,33.0,0.420561,16
Albania,4,66,28,26.1,$117.89m,UEFA,1360,68.0,43.0,0.392523,21
Bulgaria,4,68,26,28.1,$21.62m,UEFA,1350,64.0,41.0,0.373832,20
Israel,4,87,23,27.3,$49.89m,UEFA,1279,70.0,16.0,0.196262,8
Belarus,4,88,25,27.2,$15.84m,UEFA,1269,0.0,0.0,0.186916,0
Georgia,4,89,27,26.9,$57.09m,UEFA,1267,68.0,25.0,0.177570,12
Luxembourg,4,98,24,25.8,$21.37m,UEFA,1235,65.0,9.0,0.093458,4
Armenia,5,99,23,27.6,$18.65m,UEFA,1233,67.0,8.0,0.084112,4
Cyprus,5,100,28,25.4,$18.65m,UEFA,1224,63.0,11.0,0.074766,5
Faroe Islands,5,107,23,28.0,$4.59m,UEFA,1183,65.0,5.0,0.009346,2
Azerbaijan,5,108,33,25.8,$17.38m,UEFA,1180,64.0,6.0,0.000000,3
Estonia,5,108,27,26.3,$5.39m,UEFA,1180,65.0,6.0,0.000000,3

In [201]:
fetched_team = team_player_details[team_player_details['Normalize_Rank'].gt(0.4)]
fetched_team

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,,
Belgium,1,1,31,27.4,$793.10m,UEFA,1780,68.0,268.0,1.000000,134
France,1,2,26,27.6,$1.17bn,UEFA,1755,67.0,984.0,0.990654,492
England,1,4,25,25.6,$1.11bn,UEFA,1670,63.0,1667.0,0.971963,833
Portugal,1,5,24,27.4,$845.90m,UEFA,1662,70.0,344.0,0.962617,172
Spain,1,6,24,26.4,$940.50m,UEFA,1645,69.0,1035.0,0.953271,517
Italy,1,10,29,27.1,$893.20m,UEFA,1625,68.0,732.0,0.915888,366
Croatia,1,11,25,28.2,$385.00m,UEFA,1617,69.0,126.0,0.906542,63
Denmark,1,12,27,27.7,$330.33m,UEFA,1614,64.0,345.0,0.897196,172
Germany,1,13,23,26.3,$1.04bn,UEFA,1610,66.0,1216.0,0.887850,608
Netherlands,1,14,24,27.4,$566.23m,UEFA,1609,67.0,416.0,0.878505,208

In [163]:
teams_qualified = team_player_details.loc[(team_player_details['Normalize_Rank'].gt(0.4)) & 
((team_player_details['Squad_Size'] * 1.5) < team_player_details['Above_Median_Count'])]
teams_qualified

Empty DataFrame
Columns: [Rank, Squad_Size, Avg_Age, Total Value, Confideration, Points, median, count, Normalize_Rank, Above_Median_Count]
Index: []

In [208]:
team_player_details['Total Value'] = team_player_details['Total Value'].replace({'\$':''}, regex = True)
team_player_details['Total Value'] = team_player_details['Total Value'].replace({'m':''}, regex = True)
team_player_details['Total Value'] = team_player_details['Total Value'].replace({'bn':''}, regex = True)
team_player_details['Total Value'] = team_player_details['Total Value'].replace({'Th': ''}, regex=True)
team_player_details

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,,
Belgium,1,1,31,27.4,793.10,UEFA,1780,68.0,268.0,1.000000,134
France,1,2,26,27.6,1.17,UEFA,1755,67.0,984.0,0.990654,492
England,1,4,25,25.6,1.11,UEFA,1670,63.0,1667.0,0.971963,833
Portugal,1,5,24,27.4,845.90,UEFA,1662,70.0,344.0,0.962617,172
Spain,1,6,24,26.4,940.50,UEFA,1645,69.0,1035.0,0.953271,517
Italy,1,10,29,27.1,893.20,UEFA,1625,68.0,732.0,0.915888,366
Croatia,1,11,25,28.2,385.00,UEFA,1617,69.0,126.0,0.906542,63
Denmark,1,12,27,27.7,330.33,UEFA,1614,64.0,345.0,0.897196,172
Germany,1,13,23,26.3,1.04,UEFA,1610,66.0,1216.0,0.887850,608
Netherlands,1,14,24,27.4,566.23,UEFA,1609,67.0,416.0,0.878505,208
Switzerland,2,16,23,26.9,289.30,UEFA,1593,65.0,229.0,0.859813,114
Wales,2,18,25,25.2,137.97,UEFA,1562,65.0,117.0,0.841121,58
Poland,2,19,25,26.6,300.19,UEFA,1559,64.0,324.0,0.831776,162
Sweden,2,20,25,28.6,222.97,UEFA,1558,64.0,358.0,0.822430,179
Austria,2,23,29,27.2,333.82,UEFA,1531,65.0,319.0,0.794393,159
Ukraine,2,24,23,26.4,140.14,UEFA,1521,70.0,69.0,0.785047,34
Serbia,2,30,30,26.4,383.41,UEFA,1492,70.0,139.0,0.728972,69
Turkey,2,32,24,25.9,249.81,UEFA,1487,67.0,294.0,0.710280,147
Slovakia,2,34,29,27.7,135.47,UEFA,1478,69.0,54.0,0.691589,27
Romania,2,37,24,27.7,105.44,UEFA,1466,64.0,287.0,0.663551,143
Russia,3,39,26,28.4,165.66,UEFA,1461,70.0,81.0,0.644860,40
Hungary,3,40,24,28.3,65.84,UEFA,1460,70.0,35.0,0.635514,17
Republic of Ireland,3,42,27,26.4,105.38,UEFA,1456,61.0,348.0,0.616822,174
Czech Republic,3,42,25,28.2,176.50,UEFA,1456,72.0,102.0,0.616822,51
Norway,3,44,26,26.8,270.16,UEFA,1450,63.5,350.0,0.598131,175
Northern Ireland,3,45,27,27.4,50.22,UEFA,1440,64.0,81.0,0.588785,40
Iceland,3,46,23,29.0,41.75,UEFA,1438,69.0,46.0,0.579439,23
Scotland,3,48,26,28.2,274.34,UEFA,1436,65.0,277.0,0.560748,138
Greece,3,53,28,26.2,114.46,UEFA,1413,70.0,96.0,0.514019,48
Finland,4,55,25,28.7,32.89,UEFA,1411,63.0,72.0,0.495327,36
Bosnia,4,56,23,26.7,87.12,UEFA,1410,0.0,0.0,0.485981,0
Slovenia,4,62,25,27.8,148.34,UEFA,1379,68.0,61.0,0.429907,30
Montenegro,4,63,37,28.1,70.51,UEFA,1370,67.0,33.0,0.420561,16
Albania,4,66,28,26.1,117.89,UEFA,1360,68.0,43.0,0.392523,21
Bulgaria,4,68,26,28.1,21.62,UEFA,1350,64.0,41.0,0.373832,20
Israel,4,87,23,27.3,49.89,UEFA,1279,70.0,16.0,0.196262,8
Belarus,4,88,25,27.2,15.84,UEFA,1269,0.0,0.0,0.186916,0
Georgia,4,89,27,26.9,57.09,UEFA,1267,68.0,25.0,0.177570,12
Luxembourg,4,98,24,25.8,21.37,UEFA,1235,65.0,9.0,0.093458,4
Armenia,5,99,23,27.6,18.65,UEFA,1233,67.0,8.0,0.084112,4
Cyprus,5,100,28,25.4,18.65,UEFA,1224,63.0,11.0,0.074766,5
Faroe Islands,5,107,23,28.0,4.59,UEFA,1183,65.0,5.0,0.009346,2
Azerbaijan,5,108,33,25.8,17.38,UEFA,1180,64.0,6.0,0.000000,3
Estonia,5,108,27,26.3,5.39,UEFA,1180,65.0,6.0,0.000000,3

In [211]:
team_player_details['Total Value']=team_player_details['Total Value'].astype(float)

In [170]:
different_teams_qualified = team_player_details.loc[(team_player_details['Normalize_Rank'].gt(0.4)) & 
(team_player_details['Total Value'].gt(150))].reset_index()
different_teams_qualified

Empty DataFrame
Columns: [Nation, Rank, Squad_Size, Avg_Age, Total Value, Confideration, Points, median, count, Normalize_Rank, Above_Median_Count]
Index: []

In [171]:
teams_qualified = team_player_details.loc[(team_player_details['Normalize_Rank'].gt(0.3)) & 
((team_player_details['Squad_Size'] * 0.5) < team_player_details['Above_Median_Count'])]
teams_qualified

,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,
New Zealand,118.0,24.0,26.0,24.01,OFC,1149.0,63.0,35.0,0.418719,17

In [172]:
different_values = teams_qualified[~teams_qualified.isin(different_teams_qualified)].dropna()
different_values

,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,
New Zealand,118.0,24.0,26.0,24.01,OFC,1149.0,63.0,35.0,0.418719,17

In [216]:
UEFA_Higher_Pot = team_player_details[team_player_details['Pots'].isin([1, 2]) 
                                      & team_player_details['Normalize_Rank'].gt(0.4) & 
((team_player_details['Squad_Size'] * 1.5) < team_player_details['Above_Median_Count']) &
                                     (team_player_details['Total Value'].gt(150))]
UEFA_Higher_Pot

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,,
Belgium,1,1,31,27.4,793.10,UEFA,1780,68.0,268.0,1.000000,134
Portugal,1,5,24,27.4,845.90,UEFA,1662,70.0,344.0,0.962617,172
Spain,1,6,24,26.4,940.50,UEFA,1645,69.0,1035.0,0.953271,517
Italy,1,10,29,27.1,893.20,UEFA,1625,68.0,732.0,0.915888,366
Croatia,1,11,25,28.2,385.00,UEFA,1617,69.0,126.0,0.906542,63
Denmark,1,12,27,27.7,330.33,UEFA,1614,64.0,345.0,0.897196,172
Netherlands,1,14,24,27.4,566.23,UEFA,1609,67.0,416.0,0.878505,208
Switzerland,2,16,23,26.9,289.30,UEFA,1593,65.0,229.0,0.859813,114
Poland,2,19,25,26.6,300.19,UEFA,1559,64.0,324.0,0.831776,162
Sweden,2,20,25,28.6,222.97,UEFA,1558,64.0,358.0,0.822430,179
Austria,2,23,29,27.2,333.82,UEFA,1531,65.0,319.0,0.794393,159
Serbia,2,30,30,26.4,383.41,UEFA,1492,70.0,139.0,0.728972,69
Turkey,2,32,24,25.9,249.81,UEFA,1487,67.0,294.0,0.710280,147

In [219]:
UEFA_Lower_Pot = team_player_details[~team_player_details['Pots'].isin([1, 2]) 
                                      & team_player_details['Normalize_Rank'].gt(0.4) & 
((team_player_details['Squad_Size'] * 1.5) < team_player_details['Above_Median_Count']) &
                                     (team_player_details['Total Value'].gt(100))]
UEFA_Lower_Pot

,Pots,Rank,Squad_Size,Avg_Age,Total Value,Confideration,Points,median,count,Normalize_Rank,Above_Median_Count
Nation,,,,,,,,,,,
Russia,3,39,26,28.4,165.66,UEFA,1461,70.0,81.0,0.644860,40
Republic of Ireland,3,42,27,26.4,105.38,UEFA,1456,61.0,348.0,0.616822,174
Czech Republic,3,42,25,28.2,176.50,UEFA,1456,72.0,102.0,0.616822,51
Norway,3,44,26,26.8,270.16,UEFA,1450,63.5,350.0,0.598131,175
Scotland,3,48,26,28.2,274.34,UEFA,1436,65.0,277.0,0.560748,138
Greece,3,53,28,26.2,114.46,UEFA,1413,70.0,96.0,0.514019,48